package pe.com.sistradoc.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import pe.com.sistradoc.model.Tramite;
import pe.com.sistradoc.model.TramiteQueryByDeriver;
import pe.com.sistradoc.model.TramiteQueryExport;
import pe.com.sistradoc.model.TramiteQueryResumen;
import pe.com.sistradoc.model.TramiteCode;

@Repository
public interface TramiteRepository extends JpaRepository<Tramite, Long> {
	
	Tramite findByCodigoTramite(String codigoTramite);
	
	@Query(value = "select if(max(t.txt_codi_tram) is not null, "
			+ "          cast(substr(max(t.txt_codi_tram), 9) as unsigned) + 1, "
			+ "          '1') as 'codigotramite' "
			+ "  from tb_tram_padr t "
			+ " where substr(t.txt_codi_tram, 3,6) = date_format(sysdate(), \"%y%m%d\") "
		    , nativeQuery = true)
	TramiteCode getCodeTramite();
	
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite',  \r\n"
			     + "       date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso', \r\n"
			     + "       concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite',  \r\n"
			     + "       t.txt_asun_tram as 'asunto',  \r\n"
			     + "       if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			     + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante',  \r\n"
			     + "       d.txt_nomb_depe as 'dependenciaactual',  \r\n"
			     + "       (select d.txt_nomb_depe \r\n"
			     + "          from tb_depe_enti d  \r\n"
			     + "         inner join tb_fluj_tram_depe f \r\n"
		 	     + "            on d.idx_depe_enti=f.fk0_depe_enti_idx  \r\n"
			     + "         inner join tb_tipo_tram tt \r\n"
			     + "            on tt.idx_tipo_tram=f.fk1_tipo_tram_idx \r\n"
			     + "         where f.num_orde_fluj=tm.num_paso_actu + 1  \r\n"
			     + "           and tt.idx_tipo_tram=t.fk0_tipo_tram_idx  \r\n"
			     + "         limit 1) as 'dependenciadestino' \r\n"
			     + "         , tt.num_nume_dias as 'duracion' \r\n"
			     + "         , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' "
			     + "  from tb_tram_padr t  \r\n"
			     + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
			     + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
			     + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
			     + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
			     + " where tm.txt_ubic_actu='1'  \r\n"
			     + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
			     + "   and tm.num_paso_actu < (select max(f.num_orde_fluj) \r\n"
			     + "                             from tb_fluj_tram_depe f \r\n"
			     + "                            where f.fk1_tipo_tram_idx = tt.idx_tipo_tram) \r\n"
			     + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
		    , nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteDerivar();
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite',  \r\n"
		         + "       date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso', \r\n"
		         + "       concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite',  \r\n"
		         + "       t.txt_asun_tram as 'asunto',  \r\n"
		         + "       if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
		         + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante',  \r\n"
		         + "       d.txt_nomb_depe as 'dependenciaactual',  \r\n"
		         + "       (select d.txt_nomb_depe \r\n"
		         + "          from tb_depe_enti d  \r\n"
		         + "         inner join tb_fluj_tram_depe f \r\n"
	 	         + "            on d.idx_depe_enti=f.fk0_depe_enti_idx  \r\n"
		         + "         inner join tb_tipo_tram tt \r\n"
		         + "            on tt.idx_tipo_tram=f.fk1_tipo_tram_idx \r\n"
		         + "         where f.num_orde_fluj=tm.num_paso_actu + 1  \r\n"
		         + "           and tt.idx_tipo_tram=t.fk0_tipo_tram_idx  \r\n"
		         + "         limit 1) as 'dependenciadestino' \r\n"
		         + "         , tt.num_nume_dias as 'duracion' \r\n"
		         + "         , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' "
		         + "  from tb_tram_padr t  \r\n"
		         + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
		         + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
		         + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
		         + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
		         + " where tm.txt_ubic_actu='1'  \r\n"
		         + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
		         + "   and tm.num_paso_actu < (select max(f.num_orde_fluj) \r\n"
		         + "                             from tb_fluj_tram_depe f \r\n"
		         + "                            where f.fk1_tipo_tram_idx = tt.idx_tipo_tram) \r\n"
		         + "   and d.idx_depe_enti = :idDependencia \r\n"
		         + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
	    , nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteDerivar(@Param("idDependencia") Long idDependencia);
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite',  \r\n"
			     + "       tm.num_paso_actu, \r\n"
			     + "       date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso', \r\n"
			     + "       concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite',  \r\n"
			     + "       t.txt_asun_tram as 'asunto',  \r\n"
			     + "       if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			     + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante',  \r\n"
			     + "       d.txt_nomb_depe as 'dependenciaactual',  \r\n"
			     + "       (select d.txt_nomb_depe \r\n"
			     + "          from tb_depe_enti d  \r\n"
			     + "         inner join tb_tram_padr_movi tm2 \r\n"
			     + "                 on d.idx_depe_enti=tm2.fk0_depe_enti_idx  \r\n"
			     + "                and tm2.num_paso_actu=tm.num_paso_actu - 1  \r\n"
			     + "         limit 1) as 'dependenciadestino' \r\n"
			     + "         , tt.num_nume_dias as 'duracion' \r\n"
			     + "         , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' \r\n"
			     + "  from tb_tram_padr t  \r\n"
			     + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
			     + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
			     + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
			     + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
			     + " where tm.txt_ubic_actu='1'  \r\n"
			     + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
			     + "   and tm.num_paso_actu >= 1 \r\n"
			     + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
			, nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteDevolver();
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite',  \r\n"
		         + "       tm.num_paso_actu, \r\n"
		         + "       date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso', \r\n"
		         + "       concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite',  \r\n"
		         + "       t.txt_asun_tram as 'asunto',  \r\n"
		         + "       if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
		         + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante',  \r\n"
		         + "       d.txt_nomb_depe as 'dependenciaactual',  \r\n"
		         + "       (select d.txt_nomb_depe \r\n"
		         + "          from tb_depe_enti d  \r\n"
		         + "         inner join tb_tram_padr_movi tm2 \r\n"
		         + "                 on d.idx_depe_enti=tm2.fk0_depe_enti_idx  \r\n"
		         + "                and tm2.num_paso_actu=tm.num_paso_actu - 1  \r\n"
		         + "         limit 1) as 'dependenciadestino' \r\n"
		         + "         , tt.num_nume_dias as 'duracion' \r\n"
		         + "         , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' \r\n"
		         + "  from tb_tram_padr t  \r\n"
		         + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
		         + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
		         + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
		         + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
		         + " where tm.txt_ubic_actu='1'  \r\n"
		         + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
		         + "   and tm.num_paso_actu >= 1 \r\n"
		         + "   and d.idx_depe_enti = :idDependencia \r\n"
		         + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
		, nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteDevolver(@Param("idDependencia") Long idDependencia);

	
	@Query(value = "select t.txt_codi_tram as 'codigotramite',  \r\n"
			     + "       date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso', \r\n"
			     + "       concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite',  \r\n"
			     + "       t.txt_asun_tram as 'asunto',  \r\n"
			     + "       if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			     + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante',  \r\n"
			     + "       d.txt_nomb_depe as 'dependenciaactual' \r\n"
			     + "         , tt.num_nume_dias as 'duracion' \r\n"
			     + "         , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' \r\n"
			     + "  from tb_tram_padr t  \r\n"
			     + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
			     + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
			     + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
			     + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
			     + " where tm.txt_ubic_actu='1'  \r\n"
			     + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
			     + "   and tm.num_paso_actu = (select max(f.num_orde_fluj) \r\n"
			     + "                             from tb_fluj_tram_depe f \r\n"
			     + "                            where f.fk1_tipo_tram_idx = tt.idx_tipo_tram) \r\n"
			     + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
		     , nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteFinished();
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite',  \r\n"
		         + "       date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso', \r\n"
		         + "       concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite',  \r\n"
		         + "       t.txt_asun_tram as 'asunto',  \r\n"
		         + "       if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
		         + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante',  \r\n"
		         + "       d.txt_nomb_depe as 'dependenciaactual' \r\n"
		         + "         , tt.num_nume_dias as 'duracion' \r\n"
		         + "         , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' \r\n"
		         + "  from tb_tram_padr t  \r\n"
		         + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
		         + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
		         + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
		         + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
		         + " where tm.txt_ubic_actu='1'  \r\n"
		         + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
		         + "   and tm.num_paso_actu = (select max(f.num_orde_fluj) \r\n"
		         + "                             from tb_fluj_tram_depe f \r\n"
		         + "                            where f.fk1_tipo_tram_idx = tt.idx_tipo_tram) \r\n"
		         + "   and d.idx_depe_enti = :idDependencia \r\n"
		         + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
	     , nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteFinished(@Param("idDependencia") Long idDependencia);

	
	@Query(value = 
			    "select a.txt_nomb_area as 'area',  \r\n"
			  + "       d.txt_nomb_depe as 'dependenciaactual',  \r\n"
			  + "       tt.txt_nomb_tram as 'tipotramite',  \r\n"
			  + "       count(t.txt_codi_tram) as 'cantidadtramites'  \r\n"
			  + "  from tb_tram_padr t  \r\n"
			  + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram  \r\n"
			  + " inner join tb_soli_tram s on t.fk1_soli_nume_docu=s.txt_nume_docu  \r\n"
			  + " inner join tb_depe_enti d on tm.fk0_depe_enti_idx=d.idx_depe_enti  \r\n"
			  + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram  \r\n"
			  + " inner join tb_area_enti a on a.idx_area_enti=d.fk0_area_idex  \r\n"
			  + " where t.txt_esta_tram='EN TRAMITE'  \r\n"
			  + "   and tm.txt_ubic_actu='1'  \r\n"
			  + "   and fnGetRequestTime(tm.fec_deri_movi, sysdate()) > if(  \r\n"
			  + "                                                          (select ftd.num_dura_dias  \r\n"
			  + "                                                             from tb_fluj_tram_depe ftd  \r\n"
			  + "                                                            where ftd.fk1_tipo_tram_idx = tt.idx_tipo_tram  \r\n"
			  + "                                                              and tm.fk0_depe_enti_idx=ftd.fk0_depe_enti_idx  \r\n"
			  + "                                                              and ftd.num_orde_fluj=tm.num_paso_actu) is null, 1,  \r\n"
			  + "                                                          (select f.num_dura_dias  \r\n"
			  + "                                                             from tb_fluj_tram_depe f  \r\n"
			  + "                                                            where f.fk1_tipo_tram_idx = tt.idx_tipo_tram  \r\n"
			  + "                                                              and tm.fk0_depe_enti_idx=f.fk0_depe_enti_idx  \r\n"
			  + "                                                              and f.num_orde_fluj=tm.num_paso_actu))  \r\n"
			  + " group by a.txt_nomb_area,  d.txt_nomb_depe, tt.txt_nomb_tram  \r\n"
			  + " order by a.txt_nomb_area asc,  d.txt_nomb_depe asc , count(t.txt_codi_tram)  desc  "
	     , nativeQuery = true)
	List<TramiteQueryResumen> getListTramiteDeriverResumen();
	
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite'  \r\n"
			     + "     , date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso' \r\n"
			     + "     , concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite'  \r\n"
			     + "     , t.txt_asun_tram as 'asunto'  \r\n"
			     + "     , if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			     + "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante' \r\n"
			     + "     , d.txt_nomb_depe as 'dependenciaactual'  \r\n"
			     + "     , (select d.txt_nomb_depe \r\n"
			     + "          from tb_depe_enti d  \r\n"
			     + "         inner join tb_fluj_tram_depe f \r\n"
			     + "            on d.idx_depe_enti=f.fk0_depe_enti_idx  \r\n"
			     + "         inner join tb_tipo_tram tt \r\n"
			     + "            on tt.idx_tipo_tram=f.fk1_tipo_tram_idx \r\n"
			     + "         where f.num_orde_fluj=tm.num_paso_actu + 1  \r\n"
			     + "           and tt.idx_tipo_tram=t.fk0_tipo_tram_idx  \r\n"
			     + "         limit 1) as 'dependenciadestino' \r\n"
			     + "     , tt.num_nume_dias as 'duracion' \r\n"
			     + "     , fnGetRequestTime(t.fec_ingr_tram, sysdate()) as 'diastranscurridos' \r\n"
			     + "     , if(tm.num_paso_actu < (select max(f.num_orde_fluj)  \r\n"
			     + "                                from tb_fluj_tram_depe f  \r\n"
			     + "                               where f.fk1_tipo_tram_idx = tt.idx_tipo_tram)  \r\n"
			     + "         , 'por derivar'  \r\n"
			     + "         , 'por finalizar') as 'flujorealizar' \r\n"
			     + "  from tb_tram_padr t  \r\n"
			     + " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
			     + " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
			     + " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
			     + " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
			     + " where tm.txt_ubic_actu='1'  \r\n"
			     + "   and t.txt_esta_tram='EN TRAMITE' \r\n"
			     + "   and d.idx_depe_enti = :idDependencia  \r\n"
			     + " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc   "
   , nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteToAttend(@Param("idDependencia") Long idDependencia);

	
	@Query(value = "   select t.txt_codi_tram as 'codigotramite'  \r\n"
					+ "     , date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso'  \r\n"
					+ "     , concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite'   \r\n"
					+ "     , t.txt_asun_tram as 'asunto'  \r\n"
					+ "     , if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
					+ "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante'  \r\n"
					+ "     , d.txt_nomb_depe as 'dependenciaactual'  \r\n"
					+ "     , (select d.txt_nomb_depe \r\n"
					+ "          from tb_depe_enti d  \r\n"
					+ "         inner join tb_fluj_tram_depe f  on  d.idx_depe_enti=f.fk0_depe_enti_idx  \r\n"
					+ "         inner join tb_tipo_tram tt  on tt.idx_tipo_tram=f.fk1_tipo_tram_idx \r\n"
					+ "         where f.num_orde_fluj=tm.num_paso_actu + 1  \r\n"
					+ "           and tt.idx_tipo_tram=t.fk0_tipo_tram_idx  \r\n"
					+ "         limit 1) as 'dependenciadestino'  \r\n"
					+ "     , tt.num_nume_dias as 'duracion'  \r\n"
					+ "     , if(t.txt_esta_tram='EN TRAMITE', fnGetRequestTime(t.fec_ingr_tram, sysdate()), fnGetRequestTime(t.fec_ingr_tram, t.fec_term_tram)) as 'diastranscurridos'  \r\n"
					+ "     , t.txt_esta_tram as 'estadotramite'  \r\n"
					+ "     , t.num_foli_tram as 'nrofolios'  \r\n"
					+ "     , t.txt_tipo_docu as 'tipodocumentotramite'  \r\n"
					+ "     , date_format(t.fec_term_tram,'%d/%m/%y') as 'fechafin'  \r\n"
					+ "  from tb_tram_padr t  \r\n"
					+ " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
					+ " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
					+ " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
					+ " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
					+ " where tm.txt_ubic_actu='1'  \r\n"
					+ "   and t.txt_codi_tram = :codigoTramite  \r\n"
					+ " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
			, nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteFindByCodeTram(@Param("codigoTramite") String codigoTramite);
	
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite'  \r\n"
			+ "     , date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso'  \r\n"
			+ "     , concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite'   \r\n"
			+ "     , t.txt_asun_tram as 'asunto'  \r\n"
			+ "     , if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			+ "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante'  \r\n"
			+ "     , d.txt_nomb_depe as 'dependenciaactual'  \r\n"
			+ "     , (select d.txt_nomb_depe \r\n"
			+ "          from tb_depe_enti d  \r\n"
			+ "         inner join tb_fluj_tram_depe f  on  d.idx_depe_enti=f.fk0_depe_enti_idx  \r\n"
			+ "         inner join tb_tipo_tram tt  on tt.idx_tipo_tram=f.fk1_tipo_tram_idx \r\n"
			+ "         where f.num_orde_fluj=tm.num_paso_actu + 1  \r\n"
			+ "           and tt.idx_tipo_tram=t.fk0_tipo_tram_idx  \r\n"
			+ "         limit 1) as 'dependenciadestino'  \r\n"
			+ "     , tt.num_nume_dias as 'duracion'  \r\n"
			+ "     , if(t.txt_esta_tram='EN TRAMITE', fnGetRequestTime(t.fec_ingr_tram, sysdate()), fnGetRequestTime(t.fec_ingr_tram, t.fec_term_tram)) as 'diastranscurridos'  \r\n"
			+ "     , t.txt_esta_tram as 'estadotramite'  \r\n"
			+ "     , t.num_foli_tram as 'nrofolios'  \r\n"
			+ "     , t.txt_tipo_docu as 'tipodocumentotramite'  \r\n"
			+ "     , date_format(t.fec_term_tram,'%d/%m/%y') as 'fechafin'  \r\n"
			+ "  from tb_tram_padr t  \r\n"
			+ " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
			+ " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
			+ " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
			+ " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
			+ " where tm.txt_ubic_actu='1'  \r\n"
			+ "   and (s.txt_tipo_docu =:tipoDocumento and  s.txt_nume_docu = :nroDocumento)     \r\n"
			+ " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
			, nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteFindBySolicitante(@Param("tipoDocumento") String tipoDocumento, 
																@Param("nroDocumento") String nroDocumento);
	
	
	@Query(value = "select t.txt_codi_tram as 'codigotramite'  \r\n"
			+ "     , date_format(t.fec_ingr_tram,'%d/%m/%y') as 'fechaingreso'  \r\n"
			+ "     , concat(tt.idx_tipo_tram , '. ', tt.txt_nomb_tram) as 'tipotramite'   \r\n"
			+ "     , t.txt_asun_tram as 'asunto'  \r\n"
			+ "     , if(s.txt_tipo_soli='persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			+ "                                     upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli)) ) as 'solicitante'  \r\n"
			+ "     , d.txt_nomb_depe as 'dependenciaactual'  \r\n"
			+ "     , (select d.txt_nomb_depe \r\n"
			+ "          from tb_depe_enti d  \r\n"
			+ "         inner join tb_fluj_tram_depe f  on  d.idx_depe_enti=f.fk0_depe_enti_idx  \r\n"
			+ "         inner join tb_tipo_tram tt  on tt.idx_tipo_tram=f.fk1_tipo_tram_idx \r\n"
			+ "         where f.num_orde_fluj=tm.num_paso_actu + 1  \r\n"
			+ "           and tt.idx_tipo_tram=t.fk0_tipo_tram_idx  \r\n"
			+ "         limit 1) as 'dependenciadestino'  \r\n"
			+ "     , tt.num_nume_dias as 'duracion'  \r\n"
			+ "     , if(t.txt_esta_tram='EN TRAMITE', fnGetRequestTime(t.fec_ingr_tram, sysdate()), fnGetRequestTime(t.fec_ingr_tram, t.fec_term_tram)) as 'diastranscurridos'  \r\n"
			+ "     , t.txt_esta_tram as 'estadotramite'  \r\n"
			+ "     , t.num_foli_tram as 'nrofolios'  \r\n"
			+ "     , t.txt_tipo_docu as 'tipodocumentotramite'  \r\n"
			+ "     , date_format(t.fec_term_tram,'%d/%m/%y') as 'fechafin'  \r\n"
			+ "  from tb_tram_padr t  \r\n"
			+ " inner join tb_tram_padr_movi tm on t.txt_codi_tram=tm.fk1_tram_idx_tram \r\n"
			+ " inner join tb_soli_tram s  on t.fk1_soli_nume_docu=s.txt_nume_docu \r\n"
			+ " inner join tb_depe_enti d  on tm.fk0_depe_enti_idx=d.idx_depe_enti \r\n"
			+ " inner join tb_tipo_tram tt on t.fk0_tipo_tram_idx=tt.idx_tipo_tram \r\n"
			+ " where tm.txt_ubic_actu='1'  \r\n"
			+ "   and ( t.fec_ingr_tram >= :fechaInicio and  t.fec_ingr_tram < :fechaFin )   \r\n"
		  //+ "   and ( t.fec_ingr_tram >= '2024-10-25' and  t.fec_ingr_tram < '2024-10-30' )   \r\n"
			+ " order by t.fec_ingr_tram asc, tt.idx_tipo_tram asc  "
			, nativeQuery = true)
	List<TramiteQueryByDeriver> getListTramiteFindByDateRange(@Param("fechaInicio") String fechaInicio, 
															  @Param("fechaFin") String fechaFin);
	
	
	@Query(value =  
			  "     SELECT  \r\n"
			+ "            t.txt_codi_tram as 'codigotramite',  \r\n"
			+ "            date_format(t.fec_ingr_tram, '%d/%m/%Y') as 'fechaingreso',  \r\n"
			+ "            date_format(t.FEC_TERM_TRAM, '%d/%m/%Y') as 'fechatermino',  \r\n"
			+ "            tt.txt_nomb_tram as 'tipotramite',  \r\n"
			+ "            t.txt_asun_tram as 'asunto',  \r\n"
			+ "            if(s.txt_tipo_soli = 'persona', upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli, ' ', txt_apex_pate, ' ', txt_apex_mate)),  \r\n"
			+ "                                            upper(concat(s.txt_tipo_docu, '. ', s.txt_nume_docu, ' - ', s.txt_nomb_soli))  \r\n"
			+ "              ) as 'solicitante',  \r\n"
			+ "            t.NUM_FOLI_TRAM AS 'numerofolios',  \r\n"
			+ "            t.txt_esta_tram AS 'estadotramite',  \r\n"
			+ "            tt.num_nume_dias as 'duracion',  \r\n"
			+ "            fnGetRequestTime( t.fec_ingr_tram,  \r\n"
			+ "                              if(t.FEC_TERM_TRAM IS NOT NULL, t.FEC_TERM_TRAM, SYSDATE())  \r\n"
			+ "                            ) as 'diastranscurridos',  \r\n"
			+ "            '' AS 'separatortramiteflow',  \r\n"
			+ "            tm.NUM_NUME_MOVI AS 'numeromovimiento',  \r\n"
			+ "            tm.TXT_ESTA_MOVI AS 'estadomovimiento',  \r\n"
			+ "            tm.TXT_MOTI_ENVI AS 'motivomovimiento',  \r\n"
			+ "            d.txt_nomb_depe as 'dependenciaorigen',  \r\n"
			+ "            ( select d.txt_nomb_depe  \r\n"
			+ "                from tb_depe_enti d  \r\n"
			+ "               inner join tb_fluj_tram_depe f  \r\n"
			+ "                  on d.idx_depe_enti = f.fk0_depe_enti_idx  \r\n"
			+ "               inner join tb_tipo_tram tt  \r\n"
			+ "                  on tt.idx_tipo_tram = f.fk1_tipo_tram_idx  \r\n"
			+ "               where f.num_orde_fluj = tm.num_paso_actu + 1  \r\n"
			+ "                 and tt.idx_tipo_tram = t.fk0_tipo_tram_idx limit 1  \r\n"
			+ "            ) as 'dependenciadestino',  \r\n"
			+ "            date_format(tm.FEC_DERI_MOVI, '%d/%m/%Y') AS 'fechaasignacion',  \r\n"
			+ "            date_format(tm.FEC_DERI_MOVI_POST, '%d/%m/%Y') AS 'fechafin',  \r\n"
			+ "            fnGetRequestTime( tm.FEC_DERI_MOVI,  \r\n"
			+ "                              if(tm.FEC_DERI_MOVI_POST IS NOT NULL, tm.FEC_DERI_MOVI_POST, SYSDATE())  \r\n"
			+ "                            ) as 'diasasignaciontranscurrido',  \r\n"
			+ "            '' AS 'separatortramiteactivities',  \r\n"
			+ "            ta.TXT_TIPO_TARE AS 'tipotarea',  \r\n"
			+ "            ta.TXT_DESC_TARE AS 'descripciontarea',  \r\n"
			+ "            date_format(ta.FEC_REGI_TARE, '%d/%m/%Y') AS 'fecharegistrotarea'  \r\n"
			+ "       FROM tb_tram_padr t  \r\n"
			+ " inner join tb_tram_padr_movi tm  \r\n"
			+ "         on t.txt_codi_tram = tm.fk1_tram_idx_tram  \r\n"
			+ " inner join tb_soli_tram s  \r\n"
			+ "         on t.fk1_soli_nume_docu = s.txt_nume_docu  \r\n"
			+ " inner join tb_depe_enti d  \r\n"
			+ "         on tm.fk0_depe_enti_idx = d.idx_depe_enti  \r\n"
			+ " inner join tb_tipo_tram tt  \r\n"
			+ "         on t.fk0_tipo_tram_idx = tt.idx_tipo_tram  \r\n"
			+ "  left join tb_tram_padr_movi_tare ta  \r\n"
			+ "         on tm.IDX_MOVI_TRAM = ta.FK0_MOVI_TRAM_ID_MOVI  \r\n"
			+ "      WHERE (  \r\n"
			+ "                 t.txt_esta_tram = 'EN TRAMITE'  \r\n"
			+ "             OR (  \r\n"
			+ "                      t.txt_esta_tram <> 'EN TRAMITE'  \r\n"
			+ "                 AND  DATE(t.FEC_TERM_TRAM) = CURDATE()  \r\n"
			+ "                )  \r\n"
			+ "            )  \r\n"
			+ "   ORDER BY t.txt_codi_tram ASC,  \r\n"
			+ "            tm.NUM_NUME_MOVI ASC,  \r\n"
			+ "            ta.FEC_REGI_TARE ASC  "
	     , nativeQuery = true)
	List<TramiteQueryExport> getListTramiteInformations();
	
	
}
